/* Dosol App - Supabase Configuration */

export const projectId = "asavfxpvleaboucvnawb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYXZmeHB2bGVhYm91Y3ZuYXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2NzIyMDUsImV4cCI6MjA3NjI0ODIwNX0.gxaV8Bkh1a4LsQeK2ugeac0eX_WaNgZ8RRRHfk2dAMg"
export const serviceRoleKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYXZmeHB2bGVhYm91Y3ZuYXdiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDY3MjIwNSwiZXhwIjoyMDc2MjQ4MjA1fQ.riUwVct3Ay-vp8OPaxEcRt2xSewZzLdHarEY6mOd2IU"